### ISSUE TITLE
Config File Template and Creation

### ISSUE THREAD

**Issue by HMohammad2520** [Radin-System/Management_App#3]
the config file is missing in the repo for the security reasons
is there a way to create it when its not found ?
or create a template for it .

**Comment by Babuprasanth27** [comment]
Hey, I am interested in fixing this issue.

**Comment by HMohammad2520** [comment]
> Hey, I am interested in fixing this issue.

Thank you,
i already added the test config file file , but we do not know if the config strategy is valid or not
